name: CI/CD Pipeline

on:
  push:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Repository
        uses: actions/checkout@v2

      - name: Build Docker Images
        run: docker-compose build

  test_frontend:
    runs-on: ubuntu-latest

    services:
      docker:
        image: docker:latest
        options: --privileged

    steps:
      - name: Checkout Repository
        uses: actions/checkout@v2

      - name: Set up Docker Compose
        run: |
          sudo docker-compose --version
          sudo apt-get -yqq install docker-compose

      - name: Start Frontend Service
        run: docker-compose up -d frontend

      - name: Run Frontend Tests
        run: docker-compose exec -T frontend npm test -- --watchAll=false

  test_backend:
    runs-on: ubuntu-latest

    services:
      docker:
        image: docker:latest
        options: --privileged

    steps:
      - name: Checkout Repository
        uses: actions/checkout@v2

      - name: Set up Docker Compose
        run: |
          sudo docker-compose --version
          sudo apt-get -yqq install docker-compose

      - name: Start Backend Service
        run: docker-compose up -d backend

      - name: Run Backend Tests
        run: docker-compose exec -T backend npm test